#!/usr/bin/env python3
"""WP-E6b: Lyman-alpha P1D adequacy pre-flight (ENGINEERING, no real-data
comparison; T0 decision D-e, briefs/T0_DECISIONS_2026_07_27.md).

SYNTHETIC/PUBLISHED-TABLE ARITHMETIC ONLY (CLAUDE.md rule 1). This module
computes a linear-theory forward model and confronts it with the PUBLISHED
measurement UNCERTAINTIES of the DESI DR1 Lyman-alpha 1D flux power spectrum
(arXiv:2505.07974) -- never the published central VALUES as a fit target.
Tag: `ENGINEERING`, WP-E7 labeling lineage
(docs/WP_E7_DESI_RESOLVABILITY_PREFLIGHT_2026_07_27.md;
docs/WP_E6_SYNTHETIC_ADEQUACY_PREFLIGHT_2026_07_27.md is this module's direct
precedent -- same discipline, different observable). NOT `TEST`, NOT `FIT`,
NOT `SANDBOX-EXPERIMENTAL`. This answers one mechanical question: under a
specific, explicitly OPTIMISTIC linear-theory forward model, which
(ultralight mass m, mixed fraction f) cells could in principle be told
apart from f=0 by DESI DR1's own published P1D measurement precision --
nothing here is a measurement, an exclusion, or a forecast.

Reuses `pipeline/wp_e6_sweep.py` WITHOUT reimplementation:
  - `linear_matter_power_mpc3` (Eisenstein & Hu 1998 no-wiggle LCDM shape,
    sigma8-normalized, Planck18 cosmology)
  - `hu_barkana_gruzinov_fdm_transfer` (Hu, Barkana & Gruzinov 2000 pure-FDM
    suppression T_F(k))
  - `mixed_fraction_power_suppression` (the module's own linear-interpolation
    mixed-fraction ENGINEERING APPROXIMATION -- same caveat carries over
    unchanged: this is not a solved two-component Boltzmann/fluid mixing law;
    see that module's docstring for the full caveat)

New to this module:

1. **The observable: R(k_par, z; m, f) = P1D_mixed / P1D_LCDM**, in LINEAR
   THEORY, via the standard real-space (Kaiser-free) 1D projection of an
   isotropic 3D power spectrum:

       P1D(k_par) = (1/2*pi) * integral_{k_par}^{infinity} P3D(k) * k dk

   Using the RATIO cancels the unknown flux bias and much of the IGM
   modeling at first order -- the load-bearing engineering choice this WP is
   built around. This is explicitly an OPTIMISTIC proxy: no thermal
   (Doppler) broadening of the Lya forest, no nonlinear gravitational
   evolution (the FDM suppression is known to be partially regenerated by
   nonlinear collapse -- Hu, Barkana & Gruzinov 2000 note this themselves),
   and no IGM parameter marginalization (temperature-density relation,
   mean flux, thermal broadening scale -- all of which the real DESI/eBOSS
   analyses fit or marginalize over, and all of which DEGRADE sensitivity
   relative to a bias-free linear-theory ratio). Consequently: a NEGATIVE
   result here (no cell reaches 2-sigma even under this optimistic proxy) is
   a genuine stop signal for the Lya route; a POSITIVE result only licenses
   proceeding to emulator-grade modeling (the Liu, Gong & Zhou 2026 route)
   at PREDICTION_v2 pin time -- it is not itself an adequacy verdict at
   publication fidelity.

2. **Linear-in-f closed form.** Because `mixed_fraction_power_suppression`
   is LINEAR in f (S(k;m,f) = 1 - f*(1 - T_F(k;m)^2)) and the P1D projection
   integral is linear in P3D(k), the ratio has an exact closed form:

       P1D_mixed(k_par) = I_LCDM(k_par) - f * I_supp(k_par; m)
       R(k_par; m, f)   = 1 - f * rho(k_par, z; m),   rho = I_supp / I_LCDM

   where I_LCDM(k_par) = integral_{k_par}^infinity P_LCDM(k) k dk (independent
   of m, f) and I_supp(k_par; m) = integral_{k_par}^infinity (1-T_F(k;m)^2)
   P_LCDM(k) k dk (independent of f). Since T_F(k)^2 <= 1 always (HBG00's
   T_F = cos(x^3)/(1+x^8) has |cos|<=1 and (1+x^8)>=1), rho >= 0, so R is
   monotone non-increasing in f and R -> 1 as f -> 0 for ALL k, m --
   both task-required sanity properties fall out of this structure rather
   than needing to be imposed. This is verified against DIRECT numerical
   integration (not assumed) in pipeline/tests/test_wp_e6b_lya.py.

   Consequence for the statistic: Delta-chi2(m, f) = f^2 * Delta-chi2_shape(m)
   where Delta-chi2_shape(m) = sum over valid (k,z) bins of
   (rho(k,z;m)/sigma_rel(k,z))^2 -- computed ONCE per mass, not once per
   (m,f) cell, which is what makes the full 13x20 grid tractable at the
   quad-integration accuracy this module uses (~10^4 integral evaluations
   total instead of ~2x10^5).

3. **Unit conversion (redshift-consistent).** The DESI DR1 P1D table gives
   k_par in VELOCITY units (s/km, the standard Lya P1D convention), which
   maps to comoving k_par [Mpc^-1] via the local-Hubble-drift relation
   k_comoving = k_velocity * H(z)/(1+z) (H(z) from `pipeline.cosmology.
   hubble_kms_mpc`, same Planck18 cosmology used throughout this repo). This
   conversion factor changes with z, so the SAME measured k_par [s/km] value
   corresponds to a DIFFERENT comoving k_par [Mpc^-1] -- and therefore a
   different point on the (z-independent-shape) HBG00 suppression curve --
   at each of DESI's 12 redshift bins. This is how "redshift consistency" is
   achieved WITHOUT giving the suppression law itself explicit z-dependence
   (an ENGINEERING APPROXIMATION carried over unchanged from
   `wp_e6_sweep.py`: the true FDM Jeans scale evolves with redshift in
   physical/comoving units in a way this toy model does not capture -- see
   that module's docstring and the WP-E6 report's caveat 6).

4. **Validity range.** Per the DESI DR1 paper's own stated recommendation
   (arXiv:2505.07974 SECTION 4.1, "recommended k cuts" -- section number
   re-verified against the arXiv HTML during the WP-E6b audit; an earlier
   draft of this docstring and of data/MANIFEST.md said Sec.4.3): the
   paper's own words are "k > 10^-3 s km^-1 due to continuum error
   contamination" and "k < 0.5*pi/R_z, where R_z = c*Delta_lambda_DESI /
   ((1+z)*lambda_Lya) and Delta_lambda_DESI = 0.8 Angstrom, based on a
   conservative estimate of the size of the spectrograph resolution
   correction". Concretely: k_par > 1e-3 s/km
   (continuum-fitting contamination at lower k) and k_par < 0.5*pi/R_z with
   R_z = c*Delta_lambda_DESI / ((1+z)*lambda_Lya), Delta_lambda_DESI = 0.8
   Angstrom (a conservative estimate of the spectrograph resolution
   correction's uncertainty). Bins outside this range are excluded from the
   statistic entirely (not down-weighted, not imputed).
"""
from __future__ import annotations

import functools
from pathlib import Path

import numpy as np
from scipy import integrate

from pipeline.cosmology import hubble_kms_mpc
from pipeline.wp_e6_sweep import (
    hu_barkana_gruzinov_fdm_transfer,
    linear_matter_power_mpc3,
)

REPO_ROOT = Path(__file__).resolve().parent.parent
DEFAULT_DESI_DR1_P1D_CSV = (
    REPO_ROOT / "data" / "literature" / "desi_dr1_lya_p1d_2026_07_27.csv"
)

# ---------------------------------------------------------------------------
# Constants (DESI DR1 P1D paper, arXiv:2505.07974, section 2 "Estimating
# P1D" / systematics discussion -- exact numbers transcribed from the arXiv
# source this session, not from memory).
# ---------------------------------------------------------------------------
LYA_REST_ANGSTROM = 1215.67  # rest-frame Lyman-alpha wavelength
DESI_DELTA_LAMBDA_ANGSTROM = 0.8  # DESI spectrograph resolution scale, main.tex
C_KM_S = 299792.458
K_MIN_VALID_SKM = 1.0e-3  # continuum-fitting contamination floor (paper's own cut)


# ---------------------------------------------------------------------------
# 1. Unit conversion: k [s/km] (velocity/redshift space) <-> k [Mpc^-1]
#    (comoving), via the local-Hubble-drift relation.
# ---------------------------------------------------------------------------
def k_velocity_to_comoving_mpc(k_skm: np.ndarray, z: np.ndarray) -> np.ndarray:
    """Convert Lya P1D wavenumber from velocity units (s/km) to comoving
    Mpc^-1, at redshift(s) z: k_comoving = k_velocity * H(z)/(1+z).

    Standard relation used throughout the Lya P1D literature (e.g. McDonald
    2003; Palanque-Delabrouille et al. 2013): a comoving separation
    dr [Mpc] maps to a velocity separation dv [km/s] via
    dv = (H(z)/(1+z)) * dr, so wavenumbers (inverse of separation) transform
    with the INVERSE factor: k_comoving = k_velocity * H(z)/(1+z).
    """
    k_skm = np.asarray(k_skm, dtype=np.float64)
    z = np.asarray(z, dtype=np.float64)
    h_z = hubble_kms_mpc(z)  # km/s/Mpc
    return k_skm * h_z / (1.0 + z)


def k_comoving_to_velocity_skm(k_mpc: np.ndarray, z: np.ndarray) -> np.ndarray:
    """Inverse of k_velocity_to_comoving_mpc (round-trip tested)."""
    k_mpc = np.asarray(k_mpc, dtype=np.float64)
    z = np.asarray(z, dtype=np.float64)
    h_z = hubble_kms_mpc(z)
    return k_mpc * (1.0 + z) / h_z


def desi_dr1_k_max_valid_skm(z: np.ndarray) -> np.ndarray:
    """Upper edge of the DESI DR1 paper's recommended k validity range at
    redshift z: k_max = 0.5*pi / R_z, R_z = c*Delta_lambda_DESI /
    ((1+z)*lambda_Lya) [km/s] (spectrograph-resolution-correction floor,
    the paper's own conservative recommendation)."""
    z = np.asarray(z, dtype=np.float64)
    r_z_kms = C_KM_S * DESI_DELTA_LAMBDA_ANGSTROM / ((1.0 + z) * LYA_REST_ANGSTROM)
    return 0.5 * np.pi / r_z_kms


def desi_dr1_validity_mask(z: np.ndarray, k_skm: np.ndarray) -> np.ndarray:
    """Boolean mask: True where (z, k_skm) is within the DESI DR1 paper's
    own stated validity range (K_MIN_VALID_SKM <= k < k_max(z)). Bins
    outside this range are dropped from the statistic entirely."""
    z = np.asarray(z, dtype=np.float64)
    k_skm = np.asarray(k_skm, dtype=np.float64)
    k_max = desi_dr1_k_max_valid_skm(z)
    return (k_skm > K_MIN_VALID_SKM) & (k_skm < k_max)


# ---------------------------------------------------------------------------
# 2. Load the published DESI DR1 P1D table (data/literature/, git-committed).
# ---------------------------------------------------------------------------
def load_desi_dr1_p1d_table(csv_path: Path | str | None = None) -> dict:
    """Load the DESI DR1 Lya P1D table (data/MANIFEST.md provenance entry).

    Returns
    -------
    dict of ndarray: z, k_s_per_km, p1d_kms, e_stat_kms, e_syst_kms,
    e_total_kms, pfid_kms -- one row per (z, k) bin (1020 rows, 12 z bins x
    85 k bins, as published).
    """
    path = Path(csv_path) if csv_path is not None else DEFAULT_DESI_DR1_P1D_CSV
    data = np.genfromtxt(path, delimiter=",", names=True)
    return {name: np.asarray(data[name], dtype=np.float64) for name in data.dtype.names}


def sigma_rel_from_table(table: dict) -> np.ndarray:
    """Published fractional (relative) measurement uncertainty per bin:
    sigma_rel = e_total_kms / p1d_kms -- the published error on the actual
    DESI DR1 measurement, expressed as a fraction of that measurement (the
    task's sigma_rel). All bins within the paper's validity range have
    strictly positive p1d_kms (verified when this table was extracted --
    see data/MANIFEST.md), so this division is safe there; callers should
    apply desi_dr1_validity_mask() before using this array in the
    statistic."""
    return table["e_total_kms"] / table["p1d_kms"]


# ---------------------------------------------------------------------------
# 3. The P1D projection integral: general (numeric, for known-answer tests
#    and cross-checks) + the linear-in-f closed-form pieces (for the grid).
# ---------------------------------------------------------------------------
def p1d_integral_general(p3d_func, k_par_mpc: float, quad_limit: int = 300) -> float:
    """General real-space (Kaiser-free) 1D projection of an arbitrary
    isotropic 3D power spectrum:

        P1D(k_par) = (1/2*pi) * integral_{k_par}^infinity P3D(k) * k dk

    `p3d_func` is any callable k [Mpc^-1] -> P3D(k) [Mpc^3]. Used directly
    by the known-answer power-law test and as the ground truth the
    linear-in-f closed form is cross-checked against -- NOT used in the
    main grid sweep (too slow at ~10^4 evaluations if it also had to loop
    over f; see module docstring section 2)."""
    integrand = lambda k: p3d_func(k) * k  # noqa: E731
    value, _ = integrate.quad(integrand, k_par_mpc, np.inf, limit=quad_limit)
    return value / (2.0 * np.pi)


def i_lcdm_integral_mpc(k_par_mpc: float, quad_limit: int = 300) -> float:
    """I_LCDM(k_par) = integral_{k_par}^infinity P_LCDM(k) * k dk (the
    UN-normalized-by-2pi projection integral -- note this is 2*pi*P1D_LCDM,
    kept unnormalized here so ratios in i_suppression_integral_mpc's rho
    cancel the 2*pi factor exactly without re-multiplying it back in)."""
    p3d = lambda k: linear_matter_power_mpc3(np.array([k]))[0]  # noqa: E731
    integrand = lambda k: p3d(k) * k  # noqa: E731
    value, _ = integrate.quad(integrand, k_par_mpc, np.inf, limit=quad_limit)
    return value


def i_suppression_integral_mpc(k_par_mpc: float, m22: float, quad_limit: int = 300) -> float:
    """I_supp(k_par; m) = integral_{k_par}^infinity (1 - T_F(k;m)^2) *
    P_LCDM(k) * k dk -- the m-dependent, f-independent piece of the
    linear-in-f closed form (module docstring section 2)."""
    def integrand(k):
        t_f = hu_barkana_gruzinov_fdm_transfer(np.array([k]), m22)[0]
        p3d = linear_matter_power_mpc3(np.array([k]))[0]
        return (1.0 - t_f**2) * p3d * k

    value, _ = integrate.quad(integrand, k_par_mpc, np.inf, limit=quad_limit)
    return value


def rho_shape_factor(k_par_mpc: float, m22: float, quad_limit: int = 300) -> float:
    """rho(k_par; m) = I_supp(k_par; m) / I_LCDM(k_par) -- so that
    R(k_par; m, f) = 1 - f * rho(k_par; m) exactly (module docstring
    section 2). rho >= 0 always (T_F^2 <= 1), so R <= 1 and is
    non-increasing in f."""
    i_lcdm = i_lcdm_integral_mpc(k_par_mpc, quad_limit=quad_limit)
    i_supp = i_suppression_integral_mpc(k_par_mpc, m22, quad_limit=quad_limit)
    return i_supp / i_lcdm


def p1d_ratio_mixed_over_lcdm(k_par_mpc: float, m22: float, f: float,
                                quad_limit: int = 300) -> float:
    """R(k_par; m, f) = P1D_mixed(k_par) / P1D_LCDM(k_par), computed via the
    EXACT linear-in-f closed form (module docstring section 2). Equivalent
    to (but far cheaper than) computing p1d_integral_general with
    m22=m22,f=f in the numerator and m22=None in the denominator --
    equivalence is cross-checked directly in
    pipeline/tests/test_wp_e6b_lya.py, not merely asserted here."""
    if not (0.0 <= f <= 1.0):
        raise ValueError(f"f must be in [0, 1], got {f}")
    rho = rho_shape_factor(k_par_mpc, m22, quad_limit=quad_limit)
    return 1.0 - f * rho


@functools.lru_cache(maxsize=None)
def _cached_rho_shape_factor(k_par_mpc_rounded: float, m22_rounded: float) -> float:
    """Cached wrapper around rho_shape_factor, keyed on rounded floats, so
    the full (m, valid-k,z) grid -- which reuses the SAME set of comoving
    k_par values across the f loop (rho does not depend on f) -- does not
    recompute identical quad integrals. Rounding to 12 significant figures
    avoids float-repr cache misses for values that are numerically
    identical up to noise."""
    return rho_shape_factor(k_par_mpc_rounded, m22_rounded)


def rho_shape_factor_cached(k_par_mpc: float, m22: float) -> float:
    return _cached_rho_shape_factor(round(float(k_par_mpc), 12), round(float(m22), 12))


# Generated-by: Sonnet (Stream 3 agent) | Verified-by: pipeline/tests/test_wp_e6b_lya.py
# | Reviewed-by: pending T0 (Xavier)
