#!/usr/bin/env python3
"""
Supervisor for the datalake harvest daemon.

Wraps datalake_harvest.py in a restart loop with staleness monitoring and heartbeat.
Restarts on crash; emits STALE alert if harvest falls behind schedule.

Usage: python3 scripts/datalake_harvest_daemon.py [--interval 1800]
       (interval in seconds; default 1800 = 30 min)
"""

import json
import os
import shutil
import subprocess
import sys
import time
from pathlib import Path
from datetime import datetime, timedelta
import logging

REPO = Path(__file__).resolve().parent.parent
HARVEST_SCRIPT = REPO / "scripts" / "datalake_harvest.py"
HEARTBEAT_FILE = REPO / "figures" / "live" / "last_harvest.json"
STALE_FILE = REPO / "figures" / "live" / "HARVEST_STALE.md"
LOG_FILE = REPO / "logs" / "harvest_daemon.log"
DIAGNOSTICS_BRANCH = "experimental/stream4-alphaevolve-diagnostics"
DIAGNOSTICS_WORKTREE = Path(os.environ.get(
    "STREAM4_DIAGNOSTICS_WORKTREE",
    str(REPO.resolve().parent / "DarkMatterK3-Home-stream4-diagnostics"),
))
DIAGNOSTICS_FILES = ("chi2_loss_curve.png", "phenotype_corner.png", "last_harvest.json")

# Under systemd, stdout is appended to LOG_FILE by the unit (StandardOutput=append:...),
# so a stdout handler there would write every line twice. Echo to stdout only on a TTY.
_handlers = [logging.FileHandler(LOG_FILE)]
if sys.stdout.isatty():
    _handlers.append(logging.StreamHandler(sys.stdout))
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(message)s",
    handlers=_handlers,
)
logger = logging.getLogger("harvest-daemon")


def check_staleness(interval_seconds):
    """Check if last harvest is stale (older than 2x interval). Emit alert if stale."""
    if not HEARTBEAT_FILE.exists():
        logger.warning(f"Heartbeat file not found: {HEARTBEAT_FILE}")
        return False

    try:
        data = json.loads(HEARTBEAT_FILE.read_text())
        harvest_time_str = data.get("harvested_utc")
        if not harvest_time_str:
            return False

        harvest_time = datetime.fromisoformat(harvest_time_str.replace("Z", "+00:00"))
        now = datetime.utcnow().replace(tzinfo=harvest_time.tzinfo)
        elapsed = now - harvest_time
        threshold = timedelta(seconds=2 * interval_seconds)

        is_stale = elapsed > threshold
        if is_stale:
            logger.error(f"STALE: last harvest {elapsed.total_seconds():.0f}s ago (threshold {threshold.total_seconds():.0f}s)")
            emit_stale_alert(harvest_time_str, elapsed)
        else:
            logger.info(f"Heartbeat OK: {elapsed.total_seconds():.0f}s ago")
            if STALE_FILE.exists():
                STALE_FILE.unlink()
                logger.info("Cleared stale alert")

        return is_stale
    except Exception as e:
        logger.warning(f"Could not check staleness: {e}")
        return False


def emit_stale_alert(last_run, elapsed):
    """Write a markdown alert about staleness."""
    STALE_FILE.parent.mkdir(parents=True, exist_ok=True)
    alert = f"""# ⚠️ Harvest Daemon Stale

**Last successful run:** {last_run}
**Time elapsed:** {elapsed}
**Status:** The datalake harvest daemon has not completed a run in {elapsed.total_seconds() / 3600:.1f} hours.

**Action:** Check logs at `logs/harvest_daemon.log` and restart if needed.

---
*This file is automatically generated and cleared when the daemon resumes.*
"""
    STALE_FILE.write_text(alert)
    logger.info(f"Wrote stale alert to {STALE_FILE}")


def run_harvest():
    """Execute the harvest script once."""
    logger.info("Starting harvest...")
    try:
        result = subprocess.run(
            [sys.executable, str(HARVEST_SCRIPT)],
            capture_output=True,
            text=True,
            timeout=600,
        )
        if result.returncode == 0:
            logger.info("Harvest completed successfully")
            return True
        else:
            logger.error(f"Harvest failed (exit {result.returncode}): {result.stderr}")
            return False
    except subprocess.TimeoutExpired:
        logger.error("Harvest timed out (600s)")
        return False
    except Exception as e:
        logger.error(f"Harvest crashed: {e}")
        return False


def snapshot_to_diagnostics_branch():
    """Copy harvested figures into the Stream-4 diagnostics worktree and commit if state changed.

    T0 ruling 2026-09-16 (briefs/T0_RULINGS_2026_09_16.md A4): AlphaEvolve figures are not
    refreshed on main. Harvest output stays in figures/live/ (gitignored on main; heartbeat
    contract unchanged) and is snapshotted to DIAGNOSTICS_BRANCH. Commits only when the
    harvested state changes, not on every heartbeat. Push failures are logged, not fatal.
    """
    if not (DIAGNOSTICS_WORKTREE / ".git").exists():
        logger.warning(f"Diagnostics worktree missing, snapshot skipped: {DIAGNOSTICS_WORKTREE}")
        return

    def state(path):
        try:
            d = json.loads(path.read_text())
        except (OSError, json.JSONDecodeError):
            return None
        d.pop("harvested_utc", None)
        return d

    dest = DIAGNOSTICS_WORKTREE / "figures" / "live"
    new_state = state(HEARTBEAT_FILE)
    if new_state is None or new_state == state(dest / HEARTBEAT_FILE.name):
        logger.info("Diagnostics snapshot: harvested state unchanged, no commit")
        return

    def git(*args):
        return subprocess.run(
            ["git", "-C", str(DIAGNOSTICS_WORKTREE),
             "-c", "user.name=SocrateAI", "-c", "user.email=bot@socrateai.com", *args],
            capture_output=True, text=True, timeout=300,
        )

    try:
        current = git("rev-parse", "--abbrev-ref", "HEAD").stdout.strip()
        if current != DIAGNOSTICS_BRANCH:
            logger.error(f"Diagnostics worktree on '{current}', expected '{DIAGNOSTICS_BRANCH}'; snapshot skipped")
            return
        dest.mkdir(parents=True, exist_ok=True)
        for name in DIAGNOSTICS_FILES:
            src = HEARTBEAT_FILE.parent / name
            if src.exists():
                shutil.copy2(src, dest / name)
        git("add", "figures/live")
        msg = (
            f"snapshot: AlphaEvolve run {new_state.get('run_id')} gen {new_state.get('latest_generation')} "
            f"({new_state.get('n_checkpoints')} checkpoints)\n\n"
            "Automated harvest-daemon snapshot. Stream-4 EXPLORATORY SANDBOX, F5b-labeled, non-citable."
        )
        result = git("commit", "-q", "-m", msg)
        if result.returncode != 0:
            logger.error(f"Diagnostics commit failed: {result.stderr.strip() or result.stdout.strip()}")
            return
        logger.info("Diagnostics snapshot committed")
        result = git("push", "-q", "origin", DIAGNOSTICS_BRANCH)
        if result.returncode != 0:
            logger.warning(f"Diagnostics push failed (commit kept locally): {result.stderr.strip()}")
        else:
            logger.info("Diagnostics snapshot pushed")
    except Exception as e:
        logger.error(f"Diagnostics snapshot crashed: {e}")


def main():
    interval_seconds = 1800  # 30 min default
    if len(sys.argv) > 2 and sys.argv[1] == "--interval":
        try:
            interval_seconds = int(sys.argv[2])
        except ValueError:
            logger.error("Invalid interval; using default 1800s")

    LOG_FILE.parent.mkdir(parents=True, exist_ok=True)
    logger.info(f"Harvest daemon starting (interval {interval_seconds}s)")

    iteration = 0
    while True:
        iteration += 1
        logger.info(f"--- Iteration {iteration} ---")

        # Run harvest
        success = run_harvest()
        if success:
            snapshot_to_diagnostics_branch()

        # Check staleness
        check_staleness(interval_seconds)

        # Wait for next cycle
        logger.info(f"Sleeping {interval_seconds}s until next run...")
        time.sleep(interval_seconds)


if __name__ == "__main__":
    main()
