#!/usr/bin/env python3
"""WP-E6-SWEEP — synthetic injection/recovery validation of pipeline/sweep.py (ENGINEERING; no real data).

Observations are generated by the SAME emulator + K1 predictor at a known (m, f, nuisances); noise, when
added, is drawn from C₉,sys. Real P₉ is never loaded (sweep.run_sweep refuses it in synthetic mode).
Checks, each able to fail:
  S1 noiseless FDM injection (m=−22.0, f=0.35, medians): injected cell is the grid minimum, χ²_min < 1e-2
  S2 noisy FDM injections (5 seeds): coverage count of the injected cell inside the 95 % region (reported)
  S3 noiseless CDM injection (f=0): f=0 column χ²_min identical across m (structural);
     null row m=−19.1 entirely inside the 95 % region
  S4 negative control: noiseless strong-FDM injection (m=−22.9, f=0.99): some f=0 cell OUTSIDE the 95 % region
The K3 gate must pass first. Writes data/derived/wp_e6_sweep_synthetic_validation_2026_09_17/*.json.
    ~/venv/bin/python scripts/wp_e6_sweep_synthetic_validation_2026_09_17.py
"""
import json, sys, time, warnings
from pathlib import Path
import numpy as np
warnings.filterwarnings("ignore")
ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "pipeline")); sys.path.insert(0, str(ROOT / "phase1_work" / "agent1_emulator"))
import torch  # noqa: E402
torch.set_num_threads(1)   # one thread per forked worker
import emu_predict as E  # noqa: E402
import keff, sweep  # noqa: E402

OUT = ROOT / "data/derived/wp_e6_sweep_synthetic_validation_2026_09_17"
MED = json.load(open(keff.GRID_CONTROLS_JSON))["igm_nuisance_point"]
NUIS = [MED["zrei"], MED["ha"], MED["hs"], MED["taueff"]]
WORKERS = int(__import__("os").environ.get("SWEEP_WORKERS", "4"))


def main():
    OUT.mkdir(parents=True, exist_ok=True)
    pack = E.load()
    gate = keff.sweep_gate(emulator=(E.predict_pk, pack), out_path=OUT / "gate.json")
    if not gate["passes"]:
        print("K3 gate FAILED — stop", gate); return 1
    native = lambda m, f, zrei, ha, hs, taueff: E.predict_pk(pack, m, f, zrei, ha, hs, taueff, "4.2")
    predict = sweep.make_predictor(native, keff.load_k_eff(), sweep.PENDING_CORRECTIONS, "synthetic")
    cov = np.load(ROOT / "data/derived/wp_e6_sweep_cov_agg9_sys_z4p2_2026_09_17.npy")
    L = np.linalg.cholesky(cov)
    im, jf = list(sweep.M_GRID).index(-22.0), list(sweep.F_GRID).index(0.35)
    summary = {"label": sweep.SYNTHETIC_LABEL, "checks": {}}

    def run(name, m, f, seed=None):
        path = OUT / f"{name}.json"
        if path.exists():   # resume: reuse a completed sweep only if it was built for exactly this injection
            prev = json.load(open(path))
            if (prev.get("meta", {}).get("injected") == {"m": m, "f": f, "nuisances": NUIS, "noise_seed": seed}
                    and prev.get("optimizer", {}).get("n_starts") == len(sweep.PROFILE_STARTS)):
                print(f"  {name}: reused completed sweep", flush=True)
                return prev
        truth = predict(m, f, *NUIS)
        obs = truth + (L @ np.random.default_rng(seed).standard_normal(9) if seed is not None else 0.0)
        t = time.time()
        rec = sweep.run_sweep(obs, cov, predict, "synthetic", OUT / f"{name}.json", workers=WORKERS,
                              meta={"injected": {"m": m, "f": f, "nuisances": NUIS, "noise_seed": seed}})
        print(f"  {name}: {time.time() - t:.0f}s, grid min {rec['grid_minimum']}, all minima valid {rec['all_minima_valid']}, "
              f"optimizer max residual {rec['optimizer']['max_residual']:.4f}", flush=True)
        return rec

    r = run("S1_noiseless_fdm", -22.0, 0.35)
    c = np.array(r["chi2_min_grid"])
    s1 = {"injected_is_grid_minimum": bool(np.argmin(c) == im * len(sweep.F_GRID) + jf),
          "chi2_at_injected": float(c[im, jf])}
    s1["pass"] = s1["injected_is_grid_minimum"] and s1["chi2_at_injected"] < 1e-2
    summary["checks"]["S1"] = s1

    inside = []
    for seed in range(1, 6):
        r = run(f"S2_noisy_fdm_seed{seed}", -22.0, 0.35, seed)
        inside.append(not r["outside_95_region"][im][jf])
    summary["checks"]["S2"] = {"injected_inside_95_region": inside, "count": int(sum(inside)), "of": 5,
                               "note": "reported, not asserted: expected ≈95 % coverage; 5 draws is not a coverage test"}

    r = run("S3_noiseless_cdm", -22.0, 0.0)
    c = np.array(r["chi2_min_grid"]); out95 = np.array(r["outside_95_region"])
    s3 = {"f0_column_spread": float(np.ptp(c[:, 0])),
          "null_row_m_minus_19_1_any_outside_95": bool(out95[list(sweep.M_GRID).index(-19.1)].any())}
    s3["pass"] = s3["f0_column_spread"] < 1e-6 and not s3["null_row_m_minus_19_1_any_outside_95"]
    summary["checks"]["S3"] = s3

    r = run("S4_negative_control_strong_fdm", -22.9, 0.99)
    out95 = np.array(r["outside_95_region"])
    s4 = {"f0_cells_outside_95": int(out95[:, 0].sum()), "of": len(sweep.M_GRID)}
    s4["pass"] = s4["f0_cells_outside_95"] > 0
    summary["checks"]["S4"] = s4

    residuals = {p.stem: json.load(open(p))["optimizer"]["max_residual"] for p in sorted(OUT.glob("S*.json"))}
    summary["optimizer_max_residual_per_sweep"] = residuals

    # Convergence health, REPORTED not asserted (same posture as S2's coverage count). Added
    # 2026-09-21: the previous summary recorded neither, so `all minima valid False` appeared only
    # in a run log and never in the persisted artifact — and the log is not the artifact.
    # `valid_minimum` is Minuit's own flag on the retained (lowest-χ²) start. On this emulator the
    # χ² surface is flat and rugged (Migrad prints "Initial matrix not pos.def."), so the flag can
    # be False while the minimum LOCATION is stable: in S1, 7 of the 10 invalid cells have
    # optimizer_residual exactly 0.0 and an 8th has 1e-4, i.e. the extra starts found nothing
    # better; 5 of the 10 are away from any bound. That is why this
    # is reported rather than gated — turning it into a pass/fail criterion is a design change and
    # belongs to whoever fixes the sweep's acceptance rule, not to a validation run. See
    # `briefs/` for the filed note.
    conv = {}
    for path in sorted(OUT.glob("S*.json")):
        rec = json.load(open(path))
        cells = rec["cells"]
        invalid = [c for c in cells if not c["valid_minimum"]]
        conv[path.stem] = {
            "all_minima_valid": rec["all_minima_valid"],
            "cells": len(cells),
            "invalid_minima": len(invalid),
            "invalid_and_not_at_boundary": sum(1 for c in invalid if not c["at_boundary"]),
            "invalid_with_zero_optimizer_residual": sum(
                1 for c in invalid if c["optimizer_residual"] == 0.0),
            "max_optimizer_residual": rec["optimizer"]["max_residual"],
            "cells_with_residual_gt_0p1": rec["optimizer"]["cells_with_residual_gt_0p1"],
            "taueff_at_prior_box_edge": sum(
                1 for c in cells if c.get("taueff_at_prior_box_edge")),
        }
    summary["convergence_health"] = {
        "note": "reported, not asserted — see the comment in this script. `pass` below does NOT "
                "depend on these numbers; a sweep with invalid minima can still report pass.",
        "per_sweep": conv,
    }
    summary["pass"] = all(v.get("pass", True) for v in summary["checks"].values())
    summary["pass_covers"] = sorted(k for k, v in summary["checks"].items() if "pass" in v)
    (OUT / "summary.json").write_text(json.dumps(summary, indent=1))
    print(json.dumps(summary["checks"], indent=1))
    for name, c in conv.items():
        if not c["all_minima_valid"]:
            print(f"  convergence: {name} has {c['invalid_minima']}/{c['cells']} invalid minima "
                  f"({c['invalid_with_zero_optimizer_residual']} with zero optimizer residual, "
                  f"{c['invalid_and_not_at_boundary']} away from a bound) — reported, not gated",
                  flush=True)
    print("SYNTHETIC VALIDATION:", "PASS" if summary["pass"] else "FAIL",
          f"(pass covers {summary['pass_covers']}; convergence_health is reported only)")
    return 0 if summary["pass"] else 1


if __name__ == "__main__":
    sys.exit(main())
